export const HELP_LINES = [
  "One chart. Type a command here, paste JSON, or open a link.",
  "The same commands work for you, for me, or for another bot.",
  "",
  "Markets",
  "BTC 15m",
  "ETH-USD 4h",
  "venue hyperliquid",
  "BTC 15m",
  "",
  "Studies — the built-in set, no Pine required",
  "+ ema 21",
  "+ sma 50",
  "+ rsi 14",
  "+ macd 12 26 9",
  "+ bb 20",
  "+ vwap",
  "+ supertrend",
  "- rsi",
  "clear indicators",
  "",
  "Drawings",
  "hline 65000",
  "hline 65000 dashed",
  "zone 64000 67000",
  "clear drawings",
  "",
  "View",
  "style line",
  "theme light",
  "log on",
  "range 1D",
  "layout 2h",
  "",
  "Link a bot can open",
  "?symbol=coinbase:ETH-USD&tf=15&ind=ema:21,rsi:14",
  "Hyperliquid: ?symbol=hyperliquid:ETH&tf=15",
  "Add &fresh=1 to ignore the saved chart.",
  "Binance is not wired — its API refuses a browser chart.",
  "",
  "From a page that can see this one",
  'VelaDesk.run("ETH 15m; + ema 21")',
  'VelaDesk.run({ symbol: "BTC-USD", timeframe: "60", indicators: [{ type: "vwap" }] })',
  'postMessage({ channel: "vela-desk", command: "BTC 15m" })',
] as const;

export const EXAMPLES = ["BTC 15m", "ETH 4h", "+ ema 21", "+ rsi 14", "hline 100000"] as const;
